# Generated by Django 4.2.10 on 2024-02-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buyers_sellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellers',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='buyers',
        ),
        migrations.DeleteModel(
            name='sellers',
        ),
    ]
