# Generated by Django 4.2.10 on 2024-02-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0003_alter_myuser_email_alter_myuser_image_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
