# Generated by Django 4.2.9 on 2024-03-04 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sellers_group_ptr_delete_buyers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2024, 3, 4)),
        ),
    ]
