# Generated by Django 4.2.10 on 2024-02-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myuser_group_remove_myuser_groups_myuser_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='group',
        ),
    ]
