# Generated by Django 4.2.10 on 2024-02-15 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2024, 2, 15)),
        ),
    ]
