# Generated by Django 4.2.10 on 2024-02-16 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Price_ID',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2024, 2, 16)),
        ),
    ]
