# Generated by Django 4.2.10 on 2024-02-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_products_seller_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
