# Generated by Django 4.2.10 on 2024-02-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_myperson_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPerson',
        ),
    ]
