# Generated by Django 4.2.10 on 2024-02-12 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Extended_User',
        ),
    ]
