# Generated by Django 4.2.10 on 2024-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_employee_extended_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extended_user',
            name='department',
        ),
        migrations.AddField(
            model_name='extended_user',
            name='image',
            field=models.CharField(default=''),
        ),
    ]
