# Generated by Django 4.2.10 on 2024-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_extended_user_department_extended_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_user',
            name='image',
            field=models.CharField(),
        ),
    ]
