version: '3.9'
services: 
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=S3cretEXAMPLE
      - POSTGRES_USER=USER
      - POSTGRES_DB=ecommerce
    ports:
      # HOST:CONTAINER
      - 5432:5432